# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca2690c9a8aebb4e2e6008dced3bfc3431e9f824e45bded5be5a3ef492ce1ebb272a664c043f3495c47b117fd4a005c9d9ff10ed49f53540df30f8e7b145bd98

test:
  secret_key_base: 5440d9f3c2077a4154676e8254455339ea25545675336dc43fa15f30c951c7eff9bc78bd9d5813fb7517a1012e13984e479196ae7a04a66956bcbc3fb3c2dd11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
